name: Astro

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6
        with:
          node-version: "22"
          package-manager: pnpm@11.15.0
