name: Astro

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=node-version depName=node extractVersion=^v(?<version>.+)$
      NODE_VERSION: "24"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: withastro/action@3eafd002e65cc31b4f0eae0bb05450d521562247 # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
